// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	exchanges "eco_points/internal/features/exchanges"

	mock "github.com/stretchr/testify/mock"
)

// ExQuery is an autogenerated mock type for the ExQuery type
type ExQuery struct {
	mock.Mock
}

// AddExchange provides a mock function with given fields: newExchange
func (_m *ExQuery) AddExchange(newExchange exchanges.Exchange) error {
	ret := _m.Called(newExchange)

	if len(ret) == 0 {
		panic("no return value specified for AddExchange")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(exchanges.Exchange) error); ok {
		r0 = rf(newExchange)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewExQuery creates a new instance of ExQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExQuery {
	mock := &ExQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
