// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GomailUtilityInterface is an autogenerated mock type for the GomailUtilityInterface type
type GomailUtilityInterface struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: points, message, receiverEmail, receiverName
func (_m *GomailUtilityInterface) SendEmail(points int, message string, receiverEmail string, receiverName string) error {
	ret := _m.Called(points, message, receiverEmail, receiverName)

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string, string, string) error); ok {
		r0 = rf(points, message, receiverEmail, receiverName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewGomailUtilityInterface creates a new instance of GomailUtilityInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGomailUtilityInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *GomailUtilityInterface {
	mock := &GomailUtilityInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
