// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// HandlerMakeExcelInterface is an autogenerated mock type for the HandlerMakeExcelInterface type
type HandlerMakeExcelInterface struct {
	mock.Mock
}

// MakeExcel provides a mock function with given fields:
func (_m *HandlerMakeExcelInterface) MakeExcel() echo.HandlerFunc {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MakeExcel")
	}

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// NewHandlerMakeExcelInterface creates a new instance of HandlerMakeExcelInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandlerMakeExcelInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *HandlerMakeExcelInterface {
	mock := &HandlerMakeExcelInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
