// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	rewards "eco_points/internal/features/rewards"

	mock "github.com/stretchr/testify/mock"
)

// RQuery is an autogenerated mock type for the RQuery type
type RQuery struct {
	mock.Mock
}

// AddReward provides a mock function with given fields: newReward
func (_m *RQuery) AddReward(newReward rewards.Reward) error {
	ret := _m.Called(newReward)

	if len(ret) == 0 {
		panic("no return value specified for AddReward")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(rewards.Reward) error); ok {
		r0 = rf(newReward)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteReward provides a mock function with given fields: rewardID
func (_m *RQuery) DeleteReward(rewardID uint) error {
	ret := _m.Called(rewardID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReward")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(rewardID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllRewards provides a mock function with given fields: limit, offset
func (_m *RQuery) GetAllRewards(limit int, offset int) ([]rewards.Reward, int, error) {
	ret := _m.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAllRewards")
	}

	var r0 []rewards.Reward
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int) ([]rewards.Reward, int, error)); ok {
		return rf(limit, offset)
	}
	if rf, ok := ret.Get(0).(func(int, int) []rewards.Reward); ok {
		r0 = rf(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rewards.Reward)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) int); ok {
		r1 = rf(limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetRewardByID provides a mock function with given fields: rewardID
func (_m *RQuery) GetRewardByID(rewardID uint) (rewards.Reward, error) {
	ret := _m.Called(rewardID)

	if len(ret) == 0 {
		panic("no return value specified for GetRewardByID")
	}

	var r0 rewards.Reward
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (rewards.Reward, error)); ok {
		return rf(rewardID)
	}
	if rf, ok := ret.Get(0).(func(uint) rewards.Reward); ok {
		r0 = rf(rewardID)
	} else {
		r0 = ret.Get(0).(rewards.Reward)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(rewardID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateReward provides a mock function with given fields: rewardID, updatedReward
func (_m *RQuery) UpdateReward(rewardID uint, updatedReward rewards.Reward) error {
	ret := _m.Called(rewardID, updatedReward)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReward")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, rewards.Reward) error); ok {
		r0 = rf(rewardID, updatedReward)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRQuery creates a new instance of RQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *RQuery {
	mock := &RQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
