// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	locations "eco_points/internal/features/locations"

	mock "github.com/stretchr/testify/mock"
)

// ServiceLocInterface is an autogenerated mock type for the ServiceLocInterface type
type ServiceLocInterface struct {
	mock.Mock
}

// AddLocation provides a mock function with given fields: data
func (_m *ServiceLocInterface) AddLocation(data locations.LocationInterface) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for AddLocation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(locations.LocationInterface) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLocation provides a mock function with given fields: limit
func (_m *ServiceLocInterface) GetLocation(limit uint) ([]locations.LocationInterface, error) {
	ret := _m.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for GetLocation")
	}

	var r0 []locations.LocationInterface
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]locations.LocationInterface, error)); ok {
		return rf(limit)
	}
	if rf, ok := ret.Get(0).(func(uint) []locations.LocationInterface); ok {
		r0 = rf(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]locations.LocationInterface)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewServiceLocInterface creates a new instance of ServiceLocInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceLocInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceLocInterface {
	mock := &ServiceLocInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
