name: Docker Image CI

on:
  push:
    branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/imgkmb:latest
      -  
        name: connect ssh
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop ${{ secrets.CNAME }}
            docker rm ${{ secrets.CNAME }}
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/imgkmb
            docker run --name ${{ secrets.CNAME }} -p 80:8000 -d -e GOMAIL_PASSWORD=${{secrets.GOMAIL_PASSWORD}} -e GOMAIL_EMAIL=${{secrets.GOMAIL_EMAIL}} -e GOMAIL_NAME=${{secrets.GOMAIL_NAME}} -e GOMAIL_PORT=587 -e GOMAIL_HOST=${{secrets.GOMAIL_HOST}} -e DB_HOST=${{secrets.DB_HOST}} -e DB_PORT=5432 -e DB_USER=${{secrets.DB_USER}} -e DB_NAME=${{secrets.DB_NAME}} -e DB_PASSWORD=${{secrets.DB_PASSWORD}} -e JWT_SECRET=${{secrets.JWT_SECRET}} -e SCHEMA=${{secrets.SCHEMA}} -e CLOUDINARY_KEY=${{secrets.CLOUDINARY_KEY}} -e${{ secrets.DOCKERHUB_USERNAME }}/imgkmb